name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight UTC
  workflow_dispatch:  # Allows manual execution

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        id: snake
        with:
          github_user_name: DevenBhatkar
          outputs: dist/snake.svg
      - uses: actions/upload-artifact@v2
        with:
          name: snake
          path: dist/snake.svg
